services:
    php:
        build:
            context: .
            dockerfile: .docker/php/dev/Dockerfile
            args:
                USER_ID: ${USER_ID:-1000}
                USER_NAME: ${USER_NAME:-fwstats}
        entrypoint: [ "php", "artisan", "octane:start", "--host=0.0.0.0", "--port=8080", "--max-requests=1" ]
        volumes:
            - .:/app
        ports:
            - "8080:8080"
            - "5173:5173"
