version: '3.9'

services:
  web:
    image: caddy:2.5.1-alpine
    container_name: fwstats-web-container
    volumes:
      - .:/var/www/html/
      - ./docker/caddy:/etc/caddy/
    ports:
      - '8080:80'

  php:
    build: ./docker/php
    container_name: fwstats-php-container
    volumes:
      - .:/var/www/html/

  db:
    image: mysql:8.0-debian
    container_name: fwstats-db-container
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main